In [1]:
import pandas as pd

In [3]:
dataset = pd.read_csv("../pdbbind_refined_dataset.csv")

In [5]:
dataset.head()

,pdb_id,smiles,sequence,affinity
0,2r58,C[NH+](C)CCCC[C@H]([NH3+])C(=O)O,AFDWDAYLEETGSEAAPAKCFKQAQNPPNNDFKIGMKLEALDPRNV...,2.0
1,3c2f,O=P(O)(O)OC[C@H]1O[C@H](O[P@](=O)(O)OP(=O)(O)O...,PVYEHLLPVNGAWRQDVTNWLSEDVPSFDFGGYVVGSDLKEANLYC...,2.0
2,3g2y,CCc1c(C)[nH]n(-c2nnn[nH]2)c1=O,TSAVQQKLAALEKSSGGRLGVALIDTADNTQVLYRGDERFPMCSTS...,2.0
3,3pce,O=C(O)Cc1cccc(O)c1,PAQDNSRFVIRDRNWHPKALTPDYKTSIARSPRQALVSIPQSISET...,2.0
4,4qsu,C[C@H]1C=NC(=O)NC1=O,SMQEEDTFRELRIFLRNVTHRLAIDKRFRVFTKPVDPDEVPDYVTV...,2.0

In [6]:
dataset.describe()

          affinity
count  5316.000000
mean      6.392466
std       1.952730
min       2.000000
25%       4.930000
50%       6.420000
75%       7.740000
max      11.920000

In [7]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 5316 entries, 0 to 5315
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pdb_id    5316 non-null   str
 1   smiles    5314 non-null   str
 2   sequence  5316 non-null   str
 3   affinity  5316 non-null   float64
dtypes: float64(1), str(3)
memory usage: 166.3 KB